name: Cubes App
run-name: ${{ github.actor }} building cubes
on: [push]
jobs:
  Build:
    name: build-push-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      
      - id: "auth"
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
      - name: "setup gcloud sdk"
        uses: google-github-actions/setup-gcloud@v1

      - name: "gcloud info"
        run: gcloud info
    
      - name: "Docker auth"
        run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev --quiet